apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
         image: nginx
         ports:
         - containerPort: 80
         resources:
           requests:
             cpu: 200m
           limits:
             cpu: 1000m

---
apiVersion: v1
kind: Service
metadata:
  name: hpa-demo
  labels:
    app: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx