apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: af044c813730f4bc1a575168b704fc67-460450711.ap-southeast-1.elb.amazonaws.com
    http:
      paths:
      - pathType: Prefix
        path: "/backend"
        backend:
          service:
            name: myapp
            port:
              number: 8080
      - pathType: Prefix
        path: "/nginx"
        backend:
          service:
            name: mypod
            port:
              number: 80
