apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app  # Common name for both deployments (blue & green)
spec:
  selector:
    matchLabels:
      app: my-app  # Selector for pods of both deployments
  replicas: 1  # Initially deploy only 1 pod (can be scaled later)
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app  # Service targets pods from both deployments
  ports:
  - protocol: TCP
    port: 80  # Service port (matches container port)
    targetPort: 80  # Target port on pods
    nodePort: 30000  # External access port

---

# Deployment for Blue Environment (Initial Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      color: blue  # Label to differentiate blue deployment
  template:
    metadata:
      labels:
        app: my-app
        color: blue  # Label for blue pods
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

# Deployment for Green Environment (New Version Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      color: green  # Label to differentiate green deployment
  template:
    metadata:
      labels:
        app: my-app
        color: green  # Label for green pods
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
